title: Learn AI - Building Custom Computer Vision Solutions using AML
description: Microsoft labs for building Custom Computer Vision Solutions using Azure Machine Learning
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomComputerVisionwithAML
