title: Learn AI - Deep Learning solutions using Custom Vision ToolKit
description: Microsoft labs for building Deep Learning solutions using Custom Vision ToolKit
show_downloads: true
theme: jekyll-theme-cayman
repository: Azure/LearnAI-CustomComputerVisionwithAML